set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" " alternatively, pass a path where Vundle should install plugins
" "call vundle#begin('~/some/path/here')
"
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
"
" " The following are examples of different formats supported.
" " Keep Plugin commands between vundle#begin/end.
" " plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" " plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" " Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" " git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" " The sparkup vim script is in a subdirectory of this repo called vim.
" " Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" " Install L9 and avoid a Naming conflict if you've already installed a
" " different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}
"

Plugin 'Valloric/YouCompleteMe'
"Plugin 'file-line'                                                     
"Plugin 'tlib_vim'                                                      
"Plugin 'tmuxline'                                                      
"Plugin 'tslime'                                                        
"Plugin 'vim-addon-mw-utils'                                            
"Plugin 'vim-airline'                                                   
"Plugin 'vim-snipmate'                                                  
"Plugin 'vim-snippets'
Plugin 'flazz/vim-colorschemes'  " nice colors!
"Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'file:///root/myscripts/vimplugins/airline'
Plugin 'file:///root/myscripts/vimplugins/code_complete'
Plugin 'file:///root/myscripts/vimplugins/cscope_map'
Plugin 'file:///root/myscripts/vimplugins/ctrlp'
Plugin 'file:///root/myscripts/vimplugins/dwm'
Plugin 'file:///root/myscripts/vimplugins/nerdcommentor'
Plugin 'file:///root/myscripts/vimplugins/nerdtree'
Plugin 'file:///root/myscripts/vimplugins/rainbow_para'
Plugin 'file:///root/myscripts/vimplugins/snippets'
Plugin 'file:///root/myscripts/vimplugins/supertab'
Plugin 'file:///root/myscripts/vimplugins/surround'
Plugin 'file:///root/myscripts/vimplugins/syntastic'
Plugin 'file:///root/myscripts/vimplugins/tagbar'
Plugin 'file:///root/myscripts/vimplugins/tagexplorer'
Plugin 'file:///root/myscripts/vimplugins/taglist'
Plugin 'file:///root/myscripts/vimplugins/vcscommand'
Plugin 'file:///root/myscripts/vimplugins/vimfiles'
Plugin 'file:///root/myscripts/vimplugins/vundle'
Plugin 'file:///root/myscripts/vimplugins/winmanager'
Plugin 'file:///root/myscripts/vimplugins/vimstatline'
"Plugin 'file:///root/myscripts/vimplugins/YouCompleteMe'

" " All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" " To ignore plugin indent changes, instead use:
" "filetype plugin on
" "
" " Brief help
" " :PluginList       - lists configured plugins
" " :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" " :PluginSearch foo - searches for foo; append `!` to refresh local cache
" " :PluginClean      - confirms removal of unused plugins; append `!` to
" auto-approve removal
" "
" " see :h vundle for more details or wiki for FAQ
" " Put your non-Plugin stuff after this line
